### ISSUE TITLE
opengl es 能做图片剪裁么？

### ISSUE THREAD

**Issue by gif-gif** [doggycoder/AndroidOpenGLDemo#1]
RT，OPENGL ES 能直接通过Shader 把图裁剪成指定宽高么？谢谢～

**Comment by doggycoder** [comment]
通过计算获得恰当的采样坐标和顶点坐标，渲染出需要截取的图片部分。用shader直接做，就是将这部分工作放到shader里面做，所以是可以的。附：如需要保存和二次使用需要使用GLES20.glReadPixels生成Bitmap。

**Comment by gif-gif** [comment]
好的，多谢
