### ISSUE TITLE
3D模型示例的问题，以及解决方法

### ISSUE THREAD

**Issue by SimonCherryGZ** [doggycoder/AndroidOpenGLDemo#6]
您好！我在运行“3D OBJ模型”和“OBJ+MTL模型”两个示例时，无法正常显示模型，只有一片空白。
当我把渲染模式改为RENDERMODE_WHEN_DIRTY，则能正常显示模型，也就是第一次渲染的时候是没问题 的。
之后我在https://stackoverflow.com/a/10432300 找到了解决方法：
在ObjFilter和ObjFilter2的onSizeChanged方法里面添加GLES20.glViewport(0, 0, width, height)：
```
@Override
protected void onSizeChanged(int width, int height) {
    GLES20.glViewport(0, 0, width, height);
}
```
就一切正常了，能看到3D模型旋转。
P.S. 我用的手机是魅蓝Note3。

**Comment by doggycoder** [comment]
@SimonCherryGZ 恩，是的，是要加入这句，指定渲染区域。多谢你的反馈，已修复。
