### ISSUE TITLE
关于FBO与RBO绑定和内存占用的问题

### ISSUE THREAD

**Issue by o03150** [doggycoder/AndroidOpenGLDemo#9]
在创建RBO时调用了
GLES20.glFramebufferRenderbuffer(GLES20.GL_FRAMEBUFFER, GLES20.GL_DEPTH_ATTACHMENT,
				GLES20.GL_RENDERBUFFER, renderBufferId);

然后再渲染时,又再次调用此方法,是不是有点多此一举了,我注释了创建时的那个方法,一样可以运行
,还有相机+美颜那一部分,内存占用特太大了,在nexus5X上300Mb左右

**Comment by doggycoder** [comment]
@o03150 是的，挂载后直接使用即可，不必重复调用。一直在忙其他的事情，这个项目是我在学习OpenGL过程中写的Demo，所以有很多不好的地方，后来知道了也没时间去修改，以后时间充裕的时候也许会去做这件事，也许会永久的搁置。
